### PR TITLE
get the HTML and the JavaScript working and beautify it a bit.

### PR DESCRIPTION
**Pull request by fabianfrz**
* new js should not use the keyword var anymore
* menu buttons were not clickable
* update jquery and bootstrap
* fix deprecations
* little fixes for spaghetti code
* fix some crashes in the server when the file does not exist or is a directory
* direct onXXX=js callback should not be used anymore (bad coding style)
* add at least a dummy for a 404 page - it was missing

### CODE REVIEW

**Comment by isemann** [comment]
Thanks for the work, really appreciated !

**Comment by fabianfrz** [comment]
no problem - the only thing is that I did not fix line 116 (https://github.com/isemann/RPX-100/pull/5/files#diff-f0b16f371e059afcc066174f37fb73072e9d99b5a5f08a348f5def05855ca4c6R116) since it did not work before so if I would do so, I guess I would have changed the look and feel of the application. So you should decide if you want to fix it or remove the line from the source code.

**Comment by fabianfrz** [comment]
BTW: are you interested in a more modern UI framework or build system?

**Comment by isemann** [comment]
Very much interested!
will be free from another work on friday, we can chat then, if you want ?

Kind regards

Bernhard Isemann



*LinkedIn*: Bernhard Isemann <https://www.linkedin.com/in/bernhardisemann/> *|
AT*: +43 664 5703430 <http://voice.google.com/calls?a=nc,%2B436645703430>  *|
FR*: +33 6 80123506

**Comment by fabianfrz** [comment]
sure - I will call you then.

**Pull request merged**
